# Generated by Django 5.1.1 on 2024-09-12 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes', to='machine.machine')),
            ],
        ),
        migrations.CreateModel(
            name='AxisValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='machine.axis')),
            ],
            options={
                'indexes': [models.Index(fields=['axis', 'timestamp'], name='machine_axi_axis_id_764911_idx')],
            },
        ),
    ]
